services:
  src_develop:
    build:
      context: .
      dockerfile: ./datapipeline/src/Dockerfile
    volumes:
      - type: bind
        source: "./datapipeline"
        target: "/src"
    tty: true
    env_file:
      - ./datapipeline/src/.env
  # terraform_rss:
  #   container_name: terraform
  #   image: hashicorp/terraform:1.3.6
  #   env_file:
  #     - ./terraform/.env
  #   volumes:
  #     - ./terraform:/terraform
  #     - ~/.gcp:/.gcp
  #   working_dir: /terraform
  #   entrypoint: ash
  #   tty: true

  # stream_script:
  #   container_name: stream_script
  #   build:
  #     context: ./script
  #     dockerfile: dockerfile
  #   volumes:
  #     - ../stream_pipeline:/stream_pipeline
  #   working_dir: /stream_pipeline
  #   tty: true
